### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ipelupessy** [nlesc-smcm/pop-iemic-examples#1]
- [ ] pop restart from iemic script
 - [ ] iemic hotstart script
 - [ ] make sure all scripts work as advertized
 - [ ] document easy install instructions
 - [ ] POP omuse package
 - [ ] finish readme
 - [ ] add notebook versions of examples
 - [ ] make sure all scripts (and utilities) have some comments
